# Generated by Django 5.0.1 on 2024-01-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='Color',
        ),
    ]
