# Generated by Django 5.0.1 on 2024-01-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_remove_schedule_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Time',
            new_name='TimeFinish',
        ),
        migrations.AddField(
            model_name='schedule',
            name='TimeStart',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
