# Generated by Django 5.0.1 on 2024-01-24 07:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_rename_time_schedule_timefinish_schedule_timestart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Record',
        ),
    ]
