# Generated by Django 5.0.1 on 2024-01-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_rename_schedule_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Cost', models.FloatField(max_length=10)),
                ('Note', models.TextField(max_length=300)),
                ('Materials', models.TextField(max_length=300)),
            ],
        ),
    ]
