# Generated by Django 5.0.1 on 2024-01-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_operaion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operaion',
            new_name='Operation',
        ),
        migrations.RemoveField(
            model_name='record',
            name='Type',
        ),
        migrations.AddField(
            model_name='record',
            name='Operation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crm_app.operation'),
            preserve_default=False,
        ),
    ]
