# Generated by Django 5.0.1 on 2024-02-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_userinfo_usersocialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='filial',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
