# Generated by Django 5.0.1 on 2024-02-23 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_userinfo_filial_userinfo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='Cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='Materials',
            new_name='materials',
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='Note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='Guest',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='Master',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='Procedure',
            new_name='procedure',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='TimeFinish',
            new_name='timeFinish',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='TimeStart',
            new_name='timeStart',
        ),
        migrations.RemoveField(
            model_name='usersocialmedia',
            name='name',
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=300)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
