# Generated by Django 5.0.1 on 2024-02-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_socialmedia_rename_cost_procedure_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='notes',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='notes',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='note',
            new_name='notes',
        ),
    ]
