# Generated by Django 5.0.1 on 2024-02-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_record_filial_usersocialmedia_social_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='patronymic',
            field=models.CharField(default='nothing lol', max_length=50),
            preserve_default=False,
        ),
    ]
