# Generated by Django 5.0.1 on 2024-02-26 07:59

import crm_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_alter_userinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to=crm_app.models.upload_image_path),
        ),
    ]
