# Generated by Django 5.0.1 on 2024-06-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_alter_userinfo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='shortname',
            field=models.CharField(default='', max_length=5),
        ),
    ]
