# Generated by Django 5.0.1 on 2024-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_procedure_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='shortname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
